"use client";
import { useState } from "react";
import { AppShell } from "../components/AppShell";
import { Dashboard } from "../components/Dashboard";

export type Role = "Student" | "Teacher" | "Parent" | "Admin";
export default function Home() {
  const [role, setRole] = useState<Role | null>(null);
  if (role) return <AppShell role={role} onLogout={() => setRole(null)}><Dashboard role={role} /></AppShell>;
  return <Login onLogin={setRole} />;
}
function Login({ onLogin }: { onLogin: (role: Role) => void }) {
  const [role, setRole] = useState<Role>("Student");
  const [email, setEmail] = useState("alex.morgan@edusphere.edu");
  return <main className="min-h-screen bg-slate-950 p-5 sm:p-10"><div className="mx-auto grid min-h-[calc(100vh-40px)] max-w-6xl overflow-hidden rounded-[28px] bg-white shadow-2xl lg:grid-cols-[1.12fr_.88fr]"><section className="relative hidden overflow-hidden bg-indigo-600 p-12 text-white lg:block"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-indigo-400/40"/><div className="absolute -bottom-32 -left-24 h-80 w-80 rounded-full border-[40px] border-indigo-400/30"/><div className="relative"><Brand light/><div className="mt-28 max-w-md"><p className="mb-4 text-sm font-semibold uppercase tracking-[.22em] text-indigo-200">One connected campus</p><h1 className="text-5xl font-bold leading-tight">The clearer way to grow academic potential.</h1><p className="mt-6 text-lg leading-8 text-indigo-100">Bring learning, progress and people together in one thoughtful workspace.</p></div><div className="mt-20 grid grid-cols-3 gap-3 text-center"><Stat value="94%" label="Attendance"/><Stat value="1.2k" label="Learners"/><Stat value="98%" label="Connected"/></div></div></section><section className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><div className="mb-12 lg:hidden"><Brand /></div><p className="text-sm font-semibold text-indigo-600">WELCOME BACK</p><h2 className="mt-2 text-3xl font-bold">Sign in to EduSphere</h2><p className="mt-2 text-slate-500">Choose a demo role to explore the platform.</p><form onSubmit={e => { e.preventDefault(); onLogin(role); }} className="mt-8 space-y-5"><label className="block text-sm font-medium">Email<input value={email} onChange={e => setEmail(e.target.value)} type="email" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-indigo-500" /></label><label className="block text-sm font-medium">Password<input defaultValue="password" type="password" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-indigo-500" /></label><div><p className="mb-2 text-sm font-medium">Demo role</p><div className="grid grid-cols-2 gap-2">{(["Student", "Teacher", "Parent", "Admin"] as Role[]).map(r => <button type="button" key={r} onClick={() => setRole(r)} className={`rounded-xl border px-3 py-2.5 text-sm font-semibold ${role === r ? "border-indigo-600 bg-indigo-50 text-indigo-700" : "border-slate-200 text-slate-500"}`}>{r}</button>)}</div></div><button className="w-full rounded-xl bg-indigo-600 py-3.5 font-semibold text-white shadow-lg shadow-indigo-200 hover:bg-indigo-700">Login to dashboard →</button></form><p className="mt-6 text-center text-xs text-slate-400">Prototype mode · Use any email and password</p></div></section></div></main>;
}
function Brand({ light = false }: { light?: boolean }) { return <div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl font-black ${light ? "bg-white text-indigo-600" : "bg-indigo-600 text-white"}`}>E</span><span className={`text-xl font-bold ${light ? "text-white" : "text-slate-900"}`}>EduSphere</span></div>; }
function Stat({ value, label }: { value: string; label: string }) { return <div className="rounded-xl bg-white/10 py-4"><b className="block text-xl">{value}</b><span className="text-xs text-indigo-100">{label}</span></div>; }
