"use client";
import { ReactNode, createContext, useState } from "react";
import type { Role } from "../app/page";

const nav: Record<Role, string[]> = { Student: ["Overview", "My Subjects", "Assignments", "Exams", "Attendance", "Results", "Timetable", "Notifications", "AI Academic Copilot"], Teacher: ["Overview", "Students", "Attendance", "Assignments", "Submissions", "Marks", "Notices", "Class Analytics"], Parent: ["Overview", "Child Profile", "Attendance", "Academic Performance", "Assignments", "Exams", "Notifications"], Admin: ["Overview", "Students", "Teachers", "Classes", "Subjects", "Academic Calendar", "Notices", "Reports"] };
export const ActivePage = createContext("Overview");
export function AppShell({ role, onLogout, children }: { role: Role; onLogout: () => void; children: ReactNode }) {
 const [active, setActive] = useState("Overview"); const [open, setOpen] = useState(false); const name = role === "Student" ? "Alex Morgan" : role === "Teacher" ? "Priya Patel" : role === "Parent" ? "Jordan Morgan" : "Riley Carter";
 return <ActivePage.Provider value={active}><div className="min-h-screen"><aside className={`fixed inset-y-0 left-0 z-30 flex w-72 flex-col border-r border-slate-100 bg-white p-5 transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="flex items-center justify-between"><Brand/><button className="lg:hidden" onClick={() => setOpen(false)}>✕</button></div><div className="mt-8 rounded-xl bg-indigo-50 p-3"><p className="text-xs font-semibold text-indigo-500">SIGNED IN AS</p><p className="mt-1 text-sm font-bold text-indigo-950">{role}</p></div><nav className="mt-5 flex-1 space-y-1 overflow-y-auto">{nav[role].map((item, index) => <button key={item} onClick={() => { setActive(item); setOpen(false); }} className={`nav-item ${active === item ? "nav-active" : ""}`}><span className="grid h-5 w-5 place-items-center text-xs">{["▦", "◈", "✓", "▤", "◷", "★", "▣", "●", "✦"][index]}</span>{item}</button>)}</nav><button onClick={onLogout} className="nav-item border-t border-slate-100 pt-4">↪ Sign out</button></aside>{open && <button aria-label="Close menu" onClick={() => setOpen(false)} className="fixed inset-0 z-20 bg-slate-950/30 lg:hidden"/>}<main className="lg:ml-72"><header className="sticky top-0 z-10 flex h-20 items-center gap-4 border-b border-slate-100 bg-white/95 px-5 backdrop-blur sm:px-8"><button onClick={() => setOpen(true)} className="rounded-lg p-2 text-xl lg:hidden">☰</button><div className="relative hidden max-w-md flex-1 sm:block"><span className="absolute left-3 top-2.5 text-slate-400">⌕</span><input aria-label="Search" placeholder="Search students, courses, records..." className="w-full rounded-xl bg-slate-100 py-2.5 pl-9 pr-4 text-sm outline-none focus:ring-2 focus:ring-indigo-200" /></div><div className="ml-auto flex items-center gap-3"><button onClick={() => alert("You have 4 unread notifications.")} aria-label="Notifications" className="relative rounded-xl bg-slate-100 p-2.5">♧<i className="absolute right-2 top-2 h-2 w-2 rounded-full bg-rose-500"/></button><div className="hidden text-right sm:block"><p className="text-sm font-bold">{name}</p><p className="text-xs text-slate-400">{role} portal</p></div><div className="grid h-10 w-10 place-items-center rounded-full bg-indigo-100 text-sm font-bold text-indigo-700">{name.split(" ").map(n => n[0]).join("")}</div></div></header><div className="p-5 sm:p-8">{children}</div></main></div></ActivePage.Provider>;
}
function Brand() { return <div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-600 font-black text-white">E</span><span className="text-lg font-bold">EduSphere</span></div>; }
